FROM node:22-alpine
WORKDIR /app

RUN apk add --no-cache python3 py3-pip

COPY package*.json ./
RUN npm ci
COPY requirements.txt ./
RUN pip install --no-cache-dir --break-system-packages -r requirements.txt

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]
